/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import javax.swing.JOptionPane;
import sun.misc.FloatingDecimal;

/**
 *
 * @author Hardi
 */
public class POSTTEST4 extends javax.swing.JFrame {

    /**
     * Creates new form POSTTEST4
     */
    String Nama,NoHp,jenis;
    Integer Berat,Diskon;
    Float Total,uang;
    public POSTTEST4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PDasar = new javax.swing.JPanel();
        PHeaderr = new javax.swing.JPanel();
        LHeader = new javax.swing.JLabel();
        PKiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFNohp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFUkuran = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LDiskon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JBProses = new javax.swing.JButton();
        PJenis = new javax.swing.JPanel();
        RBReguler = new javax.swing.JRadioButton();
        RBExpress = new javax.swing.JRadioButton();
        JBUlang = new javax.swing.JButton();
        SliderDiskon = new javax.swing.JSlider();
        PKanan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Struct = new javax.swing.JTextArea();
        JBKeluar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                formCaretPositionChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PDasar.setBackground(new java.awt.Color(51, 51, 51));

        PHeaderr.setBackground(new java.awt.Color(51, 51, 255));
        PHeaderr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PHeaderrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PHeaderrMouseExited(evt);
            }
        });

        LHeader.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LHeader.setText("FORM PELANGGAN");

        javax.swing.GroupLayout PHeaderrLayout = new javax.swing.GroupLayout(PHeaderr);
        PHeaderr.setLayout(PHeaderrLayout);
        PHeaderrLayout.setHorizontalGroup(
            PHeaderrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHeaderrLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(LHeader)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        PHeaderrLayout.setVerticalGroup(
            PHeaderrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHeaderrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        PKiri.setBackground(new java.awt.Color(51, 51, 255));
        PKiri.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                PKiriComponentRemoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nama");

        TFName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFNameCaretUpdate(evt);
            }
        });
        TFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("No.HP");

        TFNohp.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFNohpCaretUpdate(evt);
            }
        });
        TFNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNohpActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Berat");

        TFUkuran.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFUkuranCaretUpdate(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("KG");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Diskon");

        LDiskon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LDiskon.setText("0 %");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Jenis Jasa");

        JBProses.setText("Proses");
        JBProses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBProsesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JBProsesMousePressed(evt);
            }
        });
        JBProses.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                JBProsesComponentHidden(evt);
            }
        });
        JBProses.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                JBProsesCaretPositionChanged(evt);
            }
        });
        JBProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProsesActionPerformed(evt);
            }
        });

        PJenis.setBackground(new java.awt.Color(102, 102, 102));
        PJenis.setLayout(new java.awt.GridLayout());

        buttonGroup1.add(RBReguler);
        RBReguler.setText("Reguler");

        buttonGroup1.add(RBExpress);
        RBExpress.setText("Express");

        JBUlang.setText("Ulang");
        JBUlang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JBUlangMousePressed(evt);
            }
        });

        SliderDiskon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SliderDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDiskonStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PKiriLayout = new javax.swing.GroupLayout(PKiri);
        PKiri.setLayout(PKiriLayout);
        PKiriLayout.setHorizontalGroup(
            PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PKiriLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PKiriLayout.createSequentialGroup()
                        .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)))
                        .addContainerGap())
                    .addGroup(PKiriLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PKiriLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PKiriLayout.createSequentialGroup()
                                        .addComponent(TFUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(PKiriLayout.createSequentialGroup()
                                        .addComponent(SliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PKiriLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PKiriLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PKiriLayout.createSequentialGroup()
                                .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PKiriLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(PKiriLayout.createSequentialGroup()
                                        .addComponent(JBProses)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JBUlang)
                                    .addGroup(PKiriLayout.createSequentialGroup()
                                        .addComponent(RBReguler)
                                        .addGap(0, 0, 0)
                                        .addComponent(RBExpress)))
                                .addGap(46, 46, 46))
                            .addGroup(PKiriLayout.createSequentialGroup()
                                .addComponent(PJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        PKiriLayout.setVerticalGroup(
            PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PKiriLayout.createSequentialGroup()
                .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PKiriLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PKiriLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3))
                            .addGroup(PKiriLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PKiriLayout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel5))
                                .addComponent(SliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LDiskon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PKiriLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RBReguler)
                                .addComponent(jLabel7))
                            .addComponent(RBExpress))
                        .addGap(14, 14, 14)))
                .addComponent(PJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBUlang)
                    .addComponent(JBProses))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PKanan.setBackground(new java.awt.Color(51, 51, 255));

        Struct.setEditable(false);
        Struct.setBackground(new java.awt.Color(0, 204, 255));
        Struct.setColumns(20);
        Struct.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Struct.setForeground(new java.awt.Color(255, 255, 255));
        Struct.setRows(5);
        Struct.setDisabledTextColor(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(Struct);

        JBKeluar.setText("Keluar");
        JBKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBKeluarMouseExited(evt);
            }
        });
        JBKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKeluarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Struck");

        javax.swing.GroupLayout PKananLayout = new javax.swing.GroupLayout(PKanan);
        PKanan.setLayout(PKananLayout);
        PKananLayout.setHorizontalGroup(
            PKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PKananLayout.createSequentialGroup()
                .addGroup(PKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBKeluar)
                    .addGroup(PKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PKananLayout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(jLabel8))
                        .addGroup(PKananLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PKananLayout.setVerticalGroup(
            PKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PKananLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBKeluar)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PDasarLayout = new javax.swing.GroupLayout(PDasar);
        PDasar.setLayout(PDasarLayout);
        PDasarLayout.setHorizontalGroup(
            PDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDasarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDasarLayout.createSequentialGroup()
                        .addComponent(PHeaderr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PDasarLayout.createSequentialGroup()
                        .addComponent(PKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PDasarLayout.setVerticalGroup(
            PDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PHeaderr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*EVENT HEADLING 1*/
    private void PHeaderrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHeaderrMouseEntered
        // TODO add your handling code here:
        PHeaderr.setBackground(Color.white);
        LHeader.setForeground(Color.green);

    }//GEN-LAST:event_PHeaderrMouseEntered
    /*EVENT HEADLING 2*/
    private void PHeaderrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHeaderrMouseExited
        float[] hsbvals;
        // TODO add your handling code here:
        PHeaderr.setBackground(Color.blue);
        LHeader.setForeground(Color.black);
    }//GEN-LAST:event_PHeaderrMouseExited
        /*EVENT HEADLING 3*/
    private void TFNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFNameCaretUpdate
        // TODO add your handling code here:
        if (TFName.getText().length()==0 && TFUkuran.getText().length()!=0) {
            JBProses.setEnabled(false);
        }
        else if (TFName.getText().length()!=0) {
            JBProses.setEnabled(true);
        }

    }//GEN-LAST:event_TFNameCaretUpdate
        
    private void TFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNameActionPerformed

    private void TFNohpCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFNohpCaretUpdate
        // TODO add your handling code here:

        if (TFNohp.getText().length()==0 && !TFNohp.getText().matches("[A-Z]")&& !TFNohp.getText().matches("[a-z]")) {
            JBProses.setEnabled(false);

        }
        else if (TFNohp.getText().length()!=0 && TFNohp.getText().matches("[1-9]*") ) {
            JBProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFNohpCaretUpdate

    private void TFUkuranCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFUkuranCaretUpdate
        // TODO add your handling code here:
        //VBerat= Float.valueOf(TFBerat.getText());
        Integer B;
        B =Integer.valueOf(TFUkuran.getText());
        if (B==0) {
            JBProses.setEnabled(false);
        }
        else if (B!=0) {
            JBProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFUkuranCaretUpdate

    private void JBProsesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBProsesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JBProsesMouseClicked

    private void JBProsesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBProsesMousePressed
        // TODO add your handling code here:
        /*if (TFNama.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "isi data dengan lengkap");
        }
        else if(TFNoHP.getText().equals("")){
            JOptionPane.showMessageDialog(this, "isi data dengan lengkap");
        }
        else if(TFBerat.getText().equals("")){
            JOptionPane.showMessageDialog(this, "isi data dengan lengkap");
        }
        else if(TFNoHP.getText().equals("")TFNama.getText().equals("")){
            JOptionPane.showMessageDialog(this, "isi data dengan lengkap");
        }*/

    }//GEN-LAST:event_JBProsesMousePressed

    private void JBProsesComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JBProsesComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_JBProsesComponentHidden

    private void JBProsesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JBProsesCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JBProsesCaretPositionChanged
    /*EVENT HEADLING 4*/
    private void JBProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProsesActionPerformed
        // TODO add your handling code here:
        Float VDiskon;
        Nama = TFName.getText();
        NoHp = TFNohp.getText();
        Diskon =SliderDiskon.getValue();
        if (RBReguler.isSelected()) {
            jenis= this.RBReguler.getText();
            VDiskon =Float.valueOf(SliderDiskon.getValue());
            Total = 11500*(Float.valueOf(TFUkuran.getText()))-((VDiskon/100)*11500);
            uang = Total;
        }
        else if (RBExpress.isSelected()) {

            jenis= this.RBExpress.getText();
            VDiskon =Float.valueOf(SliderDiskon.getValue());
            Total = 11500*(Float.valueOf(TFUkuran.getText()))-((VDiskon/100)*11500);
            uang = (Total*150/100);
        }
        Struct.setText("<x><x><x><x><x><x>=|STRUCK|<x><x><x><x><x><x>"+
            "\nNAMA \t: "+Nama+
            "\nNo. Hp \t: "+NoHp+
            "\nBerat Barang \t:"+TFUkuran.getText()+"KG"+
            "\nJenis Jasa \t: "+jenis+
            "\nDiskon \t: "+Diskon+"%"+
            "\nTotal \t: Rp."+uang+"0");
    }//GEN-LAST:event_JBProsesActionPerformed

    private void PKiriComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PKiriComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_PKiriComponentRemoved
    /*EVENT HEADLING 5*/
    private void JBKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBKeluarMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        int pilihan = JOptionPane.showConfirmDialog(this,"Apa anda yakin ingin Keluar","Keluar???",JOptionPane.YES_NO_OPTION);
        if (pilihan==0) {
            System.exit(0);
        }

    }//GEN-LAST:event_JBKeluarMouseClicked
        
    private void JBKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBKeluarMouseEntered
        // TODO add your handling code here:
        JBKeluar.setBackground(Color.RED);
        JBKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_JBKeluarMouseEntered

    private void JBKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBKeluarMouseExited
        // TODO add your handling code here:
        JBKeluar.setForeground(Color.BLACK);
        JBKeluar.setBackground(Color.WHITE );
    }//GEN-LAST:event_JBKeluarMouseExited

    private void JBKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBKeluarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JBKeluarActionPerformed
    /*EVENT HEADLING 6*/
    private void JBUlangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBUlangMousePressed
        // TODO add your handling code here:
        //SliderDiskon.setMinimum(0);
        TFName.setText("");
        TFNohp.setText("");
        Struct.setText("");
        TFUkuran.setText("");
        SliderDiskon.setValue(0);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_JBUlangMousePressed

    private void TFNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNohpActionPerformed
    /*EVENT HEADLING 7*/
    private void SliderDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDiskonStateChanged
        // TODO add your handling code here:
         LDiskon.setText(String.valueOf(SliderDiskon.getValue())+"%");
    }//GEN-LAST:event_SliderDiskonStateChanged
    /*EVENT HEADLING 8*/
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowActivated

    private void formCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_formCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formCaretPositionChanged
    /*EVENT HEADLING 9*/
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        TFName.setText("");
       TFNohp.setText("");
       Struct.setText("");
       TFUkuran.setText("0");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSTTEST4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSTTEST4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSTTEST4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSTTEST4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSTTEST4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBKeluar;
    private javax.swing.JButton JBProses;
    private javax.swing.JButton JBUlang;
    private javax.swing.JLabel LDiskon;
    private javax.swing.JLabel LHeader;
    private javax.swing.JPanel PDasar;
    private javax.swing.JPanel PHeaderr;
    private javax.swing.JPanel PJenis;
    private javax.swing.JPanel PKanan;
    private javax.swing.JPanel PKiri;
    private javax.swing.JRadioButton RBExpress;
    private javax.swing.JRadioButton RBReguler;
    private javax.swing.JSlider SliderDiskon;
    private javax.swing.JTextArea Struct;
    private javax.swing.JTextField TFName;
    private javax.swing.JTextField TFNohp;
    private javax.swing.JTextField TFUkuran;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
